# The numpy.random package


Overall Purpose This a sub-package of the Numpy Package in Python, the lather being a specialist package for dealing with multidimensional array of data/numbers (lists embedded within lists) in a matrix operation.
Numpy.random package effectively deals with the array of number, and generates a simulated data, when it may not be feasible to obtain the actual raw data
In [ ]:




Simple Random Data
This is used to generate random data for everyday assignment, based on variuos assumptions. There a ten (10) functions with varying outputs. The first one if the .rand function. This .rand function creates an array of in the given shape and populate it with random samples from a uniform distribution. e.g. (3, 2) or (3,5)

In [3]:
import numpy as np

In [4]:
np.random.rand (3,2)

array([[0.75734803, 0.94884824],
       [0.8787368 , 0.33840795],
       [0.12737601, 0.49308477]])

In [5]:
np.random.rand (3,5)

array([[0.11641235, 0.32458175, 0.6387501 , 0.93582433, 0.17524711],
       [0.16919503, 0.64589252, 0.69072993, 0.19481286, 0.39137178],
       [0.87630608, 0.80770734, 0.39491069, 0.30626503, 0.1238803 ]])

Permutation: This has two function (Shuffle and Permutation) which shufle the contents to achieve a modification of the existing sequence, randomly permute/return a permuted range, respectively.

Shuffle rearranges the the array along the first axis of a multidimensional array. The order is altered, however, the content remains the same.


In [7]:
arr = np.array(10)
np.random.shuffle(arr)
arr

TypeError: len() of unsized object

In [8]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([7, 8, 2, 4, 5, 6, 0, 3, 9, 1])

Use and Purpose of Distributions

1. Uniform

In probability theory and statistics, the continuous uniform distribution or rectangular distribution is a family of symmetric probability distributions such that for each member of the family, all intervals of the same length on the distribution's support are equally probable. The support is defined by the two parameters, a and b, which are its minimum and maximum values. The distribution is often abbreviated U(a,b). It is the maximum entropy probability distribution for a random variable X under no constraint other than that it is contained in the distribution's support (Source:Wikipedia)


The function is very similar to .rand

In [9]:
np.random.uniform(-9,10, 100)

array([-4.18888923,  4.07139832,  1.72419978,  1.390806  ,  4.79888526,
        0.23039723,  5.1418187 , -3.05990972, -8.31762634, -1.34634696,
        1.87178389,  2.54699298, -6.22017435, -1.06229167,  9.47898223,
       -8.40342586, -4.28125006,  6.89226917,  1.40047648,  1.27208071,
       -5.07732689,  2.5655237 , -4.39082112, -8.83615954, -3.682575  ,
        1.71787031, -2.49818196, -0.59181677, -3.4519114 , -2.84154338,
        2.58742707, -0.53342767, -3.81419133,  4.56083828, -7.194785  ,
        4.00719475,  5.65213305,  3.12922576,  0.58777416,  6.65965953,
        9.28986535, -0.15810914,  5.26187113, -8.53084328, -6.04361154,
        7.98589402, -6.39302885, -2.51910647,  2.90263263,  1.7904157 ,
       -2.58363112,  9.12551837,  2.82961956,  0.65093021,  3.05107337,
       -5.42186546, -0.34146532,  7.33216014, -8.53103313,  2.51773802,
        6.90506677,  0.19901986,  2.84339877,  9.7528786 ,  3.66524843,
        9.16622736, -5.15324821, -2.51095289,  2.56946091,  0.18